# Generated by Django 2.2.5 on 2019-11-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_main', '0002_auto_20191024_0631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['title'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='users_liked', to='QA_main.Question', verbose_name='Лайки юзеров'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(upload_to='static/images/avatars/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(blank=True, verbose_name='Текст'),
        ),
    ]
