# Generated by Django 2.2.5 on 2019-11-05 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_main', '0004_auto_20191104_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='disliked_answers',
            field=models.ManyToManyField(blank=True, related_name='As_disliked', to='QA_main.Answer', verbose_name='Liked answers'),
        ),
        migrations.AddField(
            model_name='profile',
            name='disliked_questions',
            field=models.ManyToManyField(blank=True, related_name='Qs_disliked', to='QA_main.Question', verbose_name='Liked questions'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_answers',
            field=models.ManyToManyField(blank=True, related_name='As_liked', to='QA_main.Answer', verbose_name='Liked answers'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='liked_questions',
            field=models.ManyToManyField(blank=True, related_name='Qs_liked', to='QA_main.Question', verbose_name='Liked questions'),
        ),
    ]
