# Generated by Django 2.2.5 on 2019-11-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_main', '0006_auto_20191114_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='static/images/avatars/crowd.jpg', upload_to='static/images/avatars/'),
        ),
    ]
