# Generated by Django 2.2.7 on 2019-12-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA_main', '0008_auto_20191117_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/avatars/crowd.jpg', upload_to='avatars/'),
        ),
    ]
